name: SweetAutoResidence
version: '${version}'
main: top.mrxiaom.sweet.autores.SweetAutoResidence
api-version: 1.13
folia-supported: true
softdepend:
  - PlaceholderAPI
  - CMILib
  - Residence
  - Dominion
authors: [ MrXiaoM ]
libraries:
  - "org.jetbrains:annotations:24.0.0"
commands:
  sweetautoresidence:
    description: 'The main command of SweetAutoResidence'
    aliases: [ sautoresidence, sautores, sares, sar ]
